###############################
###### GRADLE PROPERTIES ######
###############################
org.gradle.jvmargs=-Xmx4G
org.gradle.workers.max=2
org.gradle.offline=false
##########################
###### ENVIRONMENT #######
##########################
minecraft_version=1.20.1
minecraft_version_range=[1.20.1]
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)
geckolib_version_range=[4.8.3,)
terrablender_version_range=[3.0.1.10,)
curios_version_range=[5.14.1+1.20.1,)
jei_version=15.20.0.128
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1
#############################
###### MOD INFORMATION ######
#############################
mod_id=dragonminez
mod_name=DragonMineZ
mod_license=GNU General Public License v3.0
#########################
### mod_version follows the format: version.major.minor[.patch]-[tags]
### - Normally the version prefix '-beta' or '-alpha' is used for pre-release versions.
mod_version=2.1.1b
#########################
mod_group_id=com.dragonminez.mod
mod_authors=Yuseix300 & ezShokkoh
mod_credits=A special thanks to Bruno, Kyo, UB, YaibaToKen, Ben, Antro, and everyone else who supported the mod in some way.
mod_description=The DragonMine Z Mod is a Minecraft Forge Mod based on the Dragon Ball Series made by Akira Toriyama.\n\
  \ This mod adds NPCs, Transformations, Stats System, Dimensions and more!

org.gradle.java.home=G:\\Programs\\Android Studio\\jbr